// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  24

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    escape_city
    (
        init => init
        calculate_points => calculate_points
        create_escape_attempt_feed_runaway => create_escape_attempt_feed_runaway
        generate_trail_print => generate_trail_print
        create_new_runaway => create_new_runaway
        calculate_shed_weight => calculate_shed_weight
        getRunAwayById => get_runaway_by_id_endpoint
        multiply => multiply
        isReadyToMultiply => is_ready_to_multiply
        claim => claim
        totalSupply => total_supply
        approve => approve
        balanceOf => balance_of
        ownerOf => owner_of
        transfer => transfer
        transfer_from => transfer_from
        tokensOfOwner => tokens_of_owner
        isUpForAuction => is_up_for_auction
        getAuctionStatus => get_auction_status
        getCurrentWinningBid => get_current_winning_bid
        createSaleAuction => create_sale_auction
        bid => bid
        endAuction => end_auction
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
