// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    escape_city
    (
        init => init
        calculate_points => calculate_points
        create_escape_attempt_feed_runaway => create_escape_attempt_feed_runaway
        generate_trail_print => generate_trail_print
        create_new_runaway => create_new_runaway
        calculate_shed_weight => calculate_shed_weight
        multiply => multiply
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
