[package]
name = "escape-city-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.escape-city]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.1"
default-features = false
